name: mobilyft
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.3.4
  firebase_storage:
  curved_navigation_bar: ^0.3.2
  fab_circular_menu: ^0.1.4
  flutter_speed_dial: ^1.2.5
  algolia: ^0.1.7
  slide_popup_dialog: ^0.0.2
  neuomorphic_container: ^1.0.1
  nice_button: ^0.1.7
  loading_animations: ^2.1.0
  loading_card: ^0.0.5
  flutter_feather_icons: ^1.0.3
  #flutter_launcher_icons: "^0.7.3"
  giffy_dialog:
  google_maps_flutter:
  flutter_google_places:
  location: ^2.5.3
  search_map_place: ^0.1.1
  geolocator: ^5.3.0
  hidden_drawer_menu: ^1.1.2
  sliding_up_panel: ^1.0.0
  google_map_polyline:
  convex_bottom_bar:
  curved_drawer:
  animated_text_kit:
  font_awesome_flutter:
  image_picker:
  scrollable_bottom_sheet:
  url_launcher:
  permission:
  
  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth:
  cloud_firestore:
  datetime_picker_formfield: ^0.1.8
  
  flutter_slidable: "^0.5.4"

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_icons:
 # android: true
  #image_path_android: "assets/icon.png"
  #adaptive_icon_background: "assets/r4.jpg"
  #adaptive_icon_foreground: "assets/car.png"
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asets/bajajallianz.png
    - asets/Bharti-axa-.png
    - asets/hdfc.png
    - asets/icici.PNG
    - asets/iffco.png
    - asets/new-india.png
    - asets/orientalinsurance.png
    - asets/royalsundaram.png
    - asets/tata.png
    - asets/uiic.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TradeWinds
      fonts:
        - asset: Font/TradeWinds-Regular.ttf
          weight: 700
          style: italic
    - family: Nosifer
      fonts:
        - asset: Font/Nosifer-Regular.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: Font/Merriweather-Bold.ttf
          

          
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
